This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/Jef Daniels/Dropbox/Thesis 2013/Thesis/Thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (64 entries accepted, 0 rejected).
Sorting entries....done (366 comparisons).
Generating output file Thesis.acr....done (41 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
